name: Docker

on:
  push:
    branches:
      - main
  schedule:
  - cron: "42 4 * * *"

env:
  IMAGE_NAME: maven

jobs:
  push:

    strategy:
      fail-fast: false
      matrix:
        tag: [latest, 3-jdk-11]

    runs-on: ubuntu-latest
    env:
      TAG:  ${{ matrix.tag }}

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --build-arg MAVEN_TAG=$TAG --tag $IMAGE_NAME

      - name: Push to Github
        run: |
          echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker tag $IMAGE_NAME $IMAGE_ID:$TAG
          docker push $IMAGE_ID:$TAG

      - name: Push to MDSD.tools
        run: |
          echo "${{ secrets.REGISTRY_PW }}" | docker login write.docker.mdsd.tools -u github --password-stdin
          IMAGE_ID=write.docker.mdsd.tools/$IMAGE_NAME
          docker tag $IMAGE_NAME $IMAGE_ID:$TAG
          docker push $IMAGE_ID:$TAG
  
